image:
  name: hebabil/php-7.4-cli
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install
          - vendor/bin/phpunit
